plugins {
    id 'java'
    id 'application'
}

group = 'io.github.bohdanartiushenko.examples'
version = '0.0.3'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.bohdanartiushenko:basaltrock:0.2.0'
}

application {
    mainClass = 'io.github.bohdanartiushenko.examples.bedrock.ChatStreamingExample'
}

tasks.register('runChat', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'io.github.bohdanartiushenko.examples.bedrock.ChatStreamingExample'
    if (project.hasProperty('args')) {
        args project.args.split('\\s+')
    }
}

tasks.register('runKb', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'io.github.bohdanartiushenko.examples.bedrock.KnowledgeBaseRetrievalExample'
    if (project.hasProperty('args')) {
        args project.args.split('\\s+')
    }
}
